version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: bootcamp_app_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123          # set database password to test production-like environment 
      POSTGRES_DB: devops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: daxhian/devops-bootcamp-backend:latest  
    container_name: bootcamp_app_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/devops_db?schema=public
      PORT: 3001
      NEXTAUTH_SECRET: super-secret-key-for-testing-only-2026
      NEXTAUTH_URL: http://localhost:3000
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  frontend:
    image: daxhian/devops-bootcamp-frontend:latest
    container_name: bootcamp_app_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001/api

volumes:
  postgres_data:
